config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :veterans, only: %i[index]
  namespace :account, module: "accounts" do
    resource :password, only: %i[show update]
    resource :profile, only: %i[show update]
  end

  namespace :admin do
    root to: "home#index"

    resources :users, except: %i[destroy] do
      member do
        patch :lock
        patch :unlock
        patch :resend_confirmation_mail
        patch :resend_invitation_mail
      end
    end
  end

  namespace :weapp do
    resource :about, only: %i[show]
    resources :users, only: %i[show]
  end

  devise_for :users, skip: %i[registrations invitations], controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    sessions: "users/sessions"
  }

  devise_scope :user do
    resource :registrations,
             only: %i[new create],
             path: "users",
             path_names: { new: "sign_up" },
             controller: "users/registrations",
             as: :user_registration

    resource :invitations,
             only: %i[edit update],
             path: "users",
             controller: "users/invitations",
             as: :user_invitations
  end

  get "users", to: redirect("/users/sign_up")

  get "401", to: "errors#unauthorized", as: :unauthorized
  get "403", to: "errors#forbidden", as: :forbidden
  get "404", to: "errors#not_found", as: :not_found

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/accounts/application_controller.rb
# frozen_string_literal: true

module Accounts
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
    before_action :set_page_layout_data, if: -> { request.format.html? }

    protected

      def set_page_layout_data
        prepare_meta_tags title: t("accounts.#{controller_name}.show.title")
        @_sidebar_name = "accounts"
      end
  end
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

module Admin
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
    before_action :require_admin!

    before_action :set_page_layout_data, if: -> { request.format.html? }

    protected

      def set_page_layout_data
        @_sidebar_name = "admin"
      end

      def require_admin!
        unless user_signed_in? && current_user.admin?
          redirect_back fallback_location: root_url
        end
      end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :prepare_meta_tags, if: -> { request.format.html? }

  include StoreLocation
  before_action :set_page_layout_data, if: -> { request.format.html? }

  protected

    def set_page_layout_data
      @_sidebar_name = 'application'
    end

    def prepare_meta_tags(options = {})
      site_name   = Settings.seo_meta.name
      title       = nil
      description = Settings.seo_meta.description
      current_url = request.url

      # Let's prepare a nice set of defaults
      defaults = {
        site:        site_name,
        title:       title,
        description: description,
        keywords:    Settings.seo_meta.keywords,
        og: {
          url: current_url,
          site_name: site_name,
          title: title,
          description: description,
          type: "website"
        }
      }

      options.reverse_merge!(defaults)

      set_meta_tags options
    end

    def forbidden!(redirect_url: nil)
      if redirect_url.present?
        store_location redirect_url
      else
        store_location request.referrer
      end

      redirect_to forbidden_url
    end

    %w(forbidden unauthorized not_found).each do |s|
      class_eval <<-RUBY_EVAL, __FILE__, __LINE__ + 1
      def #{s}!(redirect_url: nil)
        if redirect_url.present?
          store_location redirect_url
        else
          store_location request.referrer
        end

        redirect_to #{s}_url
      end
      RUBY_EVAL
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def body_class(extra = nil)
    [
      extra,
      content_for(:body_class),
      "#{controller_path.tr('/', '-')}-#{action_name}",
      user_signed_in? ? "signed-in" : "guest"
    ].reject(&:blank?).join(" ")
  end

  def html_class(extra = nil)
    classes = [extra, content_for(:html_class), *browser.meta]
    classes << "default" unless browser.device.mobile? || browser.device.tablet?

    classes.reject(&:blank?).join(" ")
  end

  def options_for_enum_select(klass, attribute, selected = nil)
    container = klass.public_send(attribute.to_s.pluralize).map do |k, v|
      v ||= k
      [klass.human_enum_value(attribute, k), v]
    end

    options_for_select(container, selected)
  end

  # See https://docs.gitlab.com/ee/development/ee_features.html#code-in-app-views
  def render_if_exists(partial, locals = {})
    render(partial, locals) if partial_exists?(partial)
  end

  def partial_exists?(partial)
    lookup_context.exists?(partial, [], true)
  end

  def template_exists?(template)
    lookup_context.exists?(template, [], false)
  end

  # Check if a particular controller is the current one
  #
  # args - One or more controller names to check (using path notation when inside namespaces)
  #
  # Examples
  #
  #   # On TreeController
  #   current_controller?(:tree)           # => true
  #   current_controller?(:commits)        # => false
  #   current_controller?(:commits, :tree) # => true
  #
  #   # On Admin::ApplicationController
  #   current_controller?(:application)         # => true
  #   current_controller?('admin/application')  # => true
  #   current_controller?('gitlab/application') # => false
  def current_controller?(*args)
    args.any? do |v|
      v.to_s.downcase == controller.controller_name || v.to_s.downcase == controller.controller_path
    end
  end

  # Check if current controller is under the given namespace
  #
  # namespace - One or more controller names to check (using path notation when inside namespaces)
  #
  # Examples
  #
  #   # On Admin::ApplicationController
  #   current_namespace?(:application)         # => false
  #   current_namespace?('admin/application')  # => true
  #   current_namespace?('gitlab/application') # => false
  def current_namespace?(namespace)
    controller.controller_path.start_with? namespace.to_s.downcase
  end

  # Check if a particular action is the current one
  #
  # args - One or more action names to check
  #
  # Examples
  #
  #   # On Projects#new
  #   current_action?(:new)           # => true
  #   current_action?(:create)        # => false
  #   current_action?(:new, :create)  # => true
  def current_action?(*args)
    args.any? { |v| v.to_s.downcase == action_name }
  end

  # Returns active css class when condition returns true
  # otherwise returns nil.
  #
  # Example:
  #   %li{ class: active_when(params[:filter] == '1') }
  def active_when(condition)
    "active" if condition
  end
end

app/views/layouts/application/_action_bar.html.erb
<div class="action_bar">
  <%= yield :action_bar %>
</div>

app/views/layouts/application/_aside_menu.html.erb
<aside class="aside-menu">
  <button type="button" class="navbar-toggler aside-menu-toggler close" data-toggle="aside-menu-lg-show">
    <i class="fas fa-times"></i>
  </button>
  <%= yield :aside %>
</aside>

app/views/layouts/application/_breadcrumb.html.erb
<ol class="breadcrumb">
  <% breadcrumbs.each do |breadcrumb| %>
    <li class="breadcrumb-item">
      <% if breadcrumb[:link].present? %>
        <%= link_to breadcrumb[:text], breadcrumb[:link] %>
      <% else %>
        <%= breadcrumb[:text] %>
      <% end %>
    </li>
  <% end %>
  <!-- Breadcrumb Menu-->
  <li class="breadcrumb-menu d-md-down-none">
    <%= yield :breadcrumb_menu %>
  </li>
</ol>

app/views/layouts/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#3097d1">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application/_footer.html.erb
<footer class="app-footer">
  <div>
    <%= t("layouts.footer.copyright") %>
  </div>
</footer>

app/views/layouts/application/_header.html.erb
<header class="app-header navbar">
  <% if has_sidebar? %>
    <button class="navbar-toggler sidebar-toggler d-lg-none" type="button" data-toggle="sidebar-show">
      <span class="navbar-toggler-icon"></span>
    </button>
  <% end %>
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= t("layouts.header.brand") %>
  <% end %>
  <ul class="nav navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <%= current_user.email %>
        <i class="fas fa-caret-down"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <% if current_user.admin? %>
          <%= link_to t("layouts.header.account_menu.admin"), admin_root_path, class: "dropdown-item" %>
        <% end %>
        <%= link_to t("layouts.header.account_menu.profile"), account_profile_path, class: "dropdown-item" %>
        <%= link_to t("layouts.header.account_menu.sign_out"), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </li>
  </ul>
  <% if has_aside? %>
    <button class="navbar-toggler aside-menu-toggler d-md-down-none" type="button" data-toggle="aside-menu-lg-show">
      <span class="navbar-toggler-icon"></span>
    </button>
    <button class="navbar-toggler aside-menu-toggler d-lg-none" type="button" data-toggle="aside-menu-show">
      <span class="navbar-toggler-icon"></span>
    </button>
  <% end %>
</header>

app/views/layouts/application/_notice.html.erb
<% flash.each do |k, v| %>
  <div class="alert alert-<%= k %> alert-dismissible fade show">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

    <%= sanitize v.html_safe %>
  </div>
<% end %>

app/views/layouts/application/_weapp_footer.erb
<footer class="weapp-footer-style fixed-bottom">
  <ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <%= link_to '信息', weapp_user_path(id: @user.id), class: "nav-link pb-2 #{ controller_name == 'users' ? 'active' : '' }", data: { 'turbolinks-action': :replace } %>
    </li>
    <li class="nav-item">
      <%= link_to '关于', weapp_about_path, class: "nav-link pb-2 #{ controller_name == 'abouts' ? 'active' : '' }", data: { 'turbolinks-action': :replace } %>
    </li>
  </ul>
</footer>